### ISSUE TITLE
BUG!!!

### ISSUE THREAD

**Issue by jhqwqmc** [xxAROX/WD-Forms#13]
Starting WaterdogPE....
01:23:19 [INFO ] Starting WaterDogPE proxy software!
01:23:19 [INFO ] Software Version: 1.2.4
01:23:19 [INFO ] Build Version: release
01:23:19 [INFO ] Development Build: false
01:23:19 [INFO ] Software Authors: WaterdogTEAM
01:23:19 [INFO ] Discovered branch 127f489421d8d77444fcc99f7ff8c860409a4bc4 commitId 127f489
01:23:19 [INFO ] Using NIO channel implementation as default!
Exception in thread "WaterdogPE-main" java.lang.NoClassDefFoundError: dev/waterdog/waterdogpe/network/protocol/updaters/ProtocolCodecUpdater
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3405)
        at java.base/java.lang.Class.getConstructor0(Class.java:3610)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2786)
        at dev.waterdog.waterdogpe.plugin.PluginLoader.loadPluginJAR(PluginLoader.java:58)
        at dev.waterdog.waterdogpe.plugin.PluginManager.loadPlugin(PluginManager.java:101)
        at java.base/java.util.TreeMap.forEach(TreeMap.java:1282)
        at dev.waterdog.waterdogpe.plugin.PluginManager.loadPluginsIn(PluginManager.java:78)
        at dev.waterdog.waterdogpe.plugin.PluginManager.<init>(PluginManager.java:52)
        at dev.waterdog.waterdogpe.ProxyServer.<init>(ProxyServer.java:166)
        at dev.waterdog.waterdogpe.WaterdogPE.main(WaterdogPE.java:63)
Caused by: java.lang.ClassNotFoundException: dev.waterdog.waterdogpe.network.protocol.updaters.ProtocolCodecUpdater
        at dev.waterdog.waterdogpe.plugin.PluginClassLoader.findClass(PluginClassLoader.java:46)
        at dev.waterdog.waterdogpe.plugin.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 11 more
请按任意键继续. . .

**Comment by xxAROX** [comment]
*This plugin only works for the Snapshot builds(V2) of @WaterdogPE*
